name: editable_list_view
description: A new Flutter package project.
version: 0.0.1
homepage: https://github.com/tmcmaster/editable_list_view/blob/main/README.md

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.2.0"

flutter:
  uses-material-design: true

dependencies:
  flutter:
    sdk: flutter
  uuid:
  hooks_riverpod: ^0.14.0+4
  flutter_workbench:
    git:
      url: https://github.com/tmcmaster/flutter_workbench.git
  expandable: ^5.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic:
  lint:
  test:
